### ISSUE TITLE
Investigate hosting for signed builds

### ISSUE THREAD

**Issue by 6a68** [mozilla-lockbox/lockbox-addon#105]
In order to start dogfooding internally, we need to put our signed builds (#44) on a website somewhere. Let's figure out that distribution step.

**Comment by jbuck** [comment]
Yeah, it's pretty easy to deploy a static site that you can upload to. When would this by desired by? And who needs the AWS credentials?

**Comment by linuxwolf** [comment]
I think the most expedient thing we could do is publish a "prerelease" GH release; our CircleCI is already setup with that.

For a static site, we do have https://lockbox.firefox.com already, but we'd have to be very deliberate with publication there, to be sure we don't conflict with supported launches and updates.

**Comment by linuxwolf** [comment]
The current consensus is to use the existing public website to either host or link to the signed XPI.  As a very limited number of releases are planned, each deployment will be manually performed.
