### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-addon#11]
improves coverage; decreases risk of unintended breakage

**Comment by linuxwolf** [comment]
I'm afraid it is a matter of walking through, though a lot was removed when migrating from `lockbox-extension`.  For the purposes of this tech debt, I think it sufficient we don't have whole files that are untested and unused.

**Comment by meandavejustice** [comment]
I ran the coverage report to see if that would shed some light on where some dead code may be.

Here are the results:
```
96.34% Statements 815/846
91.59% Branches 305/333
97.81% Functions 313/320
96.39% Lines 800/830
```

Which is _very_ impressive, but not helpful with finding dead code

**Comment by linuxwolf** [comment]
Consensus is there is little-to-no dead code left to worry about.  Closing.
