### ISSUE TITLE
No Indication if User happens to add a duplicate entry

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-addon#110]
If the following fields all identical, Firefox throws an error that is not handled:

* hostname (visible as "Website Address")
* submitFormURL (hidden)
* httpRealm (hidden)
* username (visible as "username")

Note this is most likely to happen when adding an entry, but could also occur when a user attempts to update an existing entry.

## Acceptance Criteria

* If a duplicate is found, a notification is displayed to the user that this entry already exists, with a link to navigate to the existing entry, however the user is left on the filled "New Entry" page in case they want to change either the username or the web address in order to clear the errors and create a new entry.

## Visual

**Invision:** https://mozilla.invisionapp.com/share/ENOL84959AK#/355565077_Logins_-_New_Entry_-_Filled-_Duplicate_Error_-Light- 
**Zeplin:** https://zpl.io/a7O65d8

**Comment by meandavejustice** [comment]
We may just use the same notification alert we use for firefox sync errors here, animate it maybe

**Comment by linuxwolf** [comment]
The intent is to handle cases where some fields are not identical to an existing record.

To be clear, the underlying `nsLoginManager` rejects the add (or update) if all of the fields mentioned in the description above are identical to an existing record.  The current implement simply leaves the user with no feedback -- the edit/add entry view remains visible, yet there is no indication that anything at all happened.

**Comment by changecourse** [comment]
I added designs and updated acceptance criteria to the description above.

I think the primary use case for someone getting to this state would be accidentally creating a duplicative entry; therefore, I've added a bit to the criteria to have the ability to help guide someone to the matching entry within the notification.

**Comment by linuxwolf** [comment]
@changecourse I think the prototype looks very doable.  My only question: is the this dismissed when the user starts changing anything? (assume yes)

Thanks again!

**Comment by changecourse** [comment]
>Is the this dismissed when the user starts changing anything?

Good question; I think we should remove the error validation state from the fields, but preserve the dialog (in case someone still wants to quickly link to the potentially duplicative entry), and only clear that on new submission attempt.

**Comment by linuxwolf** [comment]
My concern with leaving it open is the potential of user confusion -- if whatever changes someone makes still conflicts (maybe with a different entry), how is that communicated to the user?

**Comment by changecourse** [comment]
I suppose; though usually only form field error validation changes state in real time... the error to present the dialog was thrown on submission, so it makes sense to be persistent in case someone chooses to use the link to a potential duplicate, or expects it to clear on re-submission. It's not typically common for an error dialog to clear in real time, which will readjust the vertical position of the content area.

**Comment by meandavejustice** [comment]
working branch at [110-duplicate-entry-notification](https://github.com/mozilla-lockbox/lockbox-addon/tree/110-duplicate-entry-notification)
