### ISSUE TITLE
Update doorhanger list view

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-addon#12]
When I want to take inventory of the accounts I have saved for a specific URL, I want an easy way to navigate the list to make decisions around next actions (view details, copy, manage).

## Acceptance criteria
* Should align to photon design standards
* Should feel native to the Firefox browser

## Visual Design
**Zeplin**
Default (search focused): https://zpl.io/2EPeOpy
Filtered: https://zpl.io/25G8Jln
Entry Hover: https://zpl.io/andg3Rk
Info Button Hover: https://zpl.io/bJ9JDAJ
Bottom Button ("Open Lockbox") Hover: https://zpl.io/V4QNvg4

**Comment by meandavejustice** [comment]
Been working on this but I can't self assign
