### ISSUE TITLE
Investigate export to m-c tree

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-addon#122]

**Comment by 6a68** [comment]
The Screenshots scripts/configs aren't super reusable, and they're in python, which is not a huge deal, but does add needless complexity to the overall developer setup.

The [a-s scripts](https://github.com/mozilla/activity-stream/blob/master/package.json#L109-L114), on the other hand, are just npm run scripts. Seems like this approach will work pretty easily for us, with the minor complication of supporting both windows and *nix builds. Complications will include (1) generating the moz.build file correctly, and (2) transforming / formatting the locales files correctly.

I'll file a followup bug to actually do the implementation. Even if the moz.build is rolled by hand, shouldn't be more than a 3 point followup issue.
