### ISSUE TITLE
"unbrand" the extension 

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-addon#126]
We're aiming to launch the current management experience in the desktop browser. We need to remove the "Firefox Lockbox" branding.

This probably means we also need to update the 'empty' state (ie remove Lockie).

@changecourse can you help identify what needs to happen here in the next sprint?

**Comment by linuxwolf** [comment]
Looking over the designs again, I _think_ the intent was to default to the fist entry in the list (or the "how to add an entry" explainer #31 if none).  If true, a defined empty/unselected state is probably unnecessary.

**Comment by changecourse** [comment]
Correct, first entry as selected by default. 

May need to regroup on treatment of header in general... will discuss with @linuxwolf soon.
