### ISSUE TITLE
Stable URL for management UI(about:logins)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-addon#13]
When I want to access my saved logins, I want to be able to do that similarly to how I already navigate the web, by typing in a url or clicking a saved bookmark.

## Acceptance criteria
* Management tab should be navigable from somewhere else (e.g., clicking a link) and back
* If linked, Management interface URL should open in new tab or window
* Should show up in recently closed tabs
* Should be able to be bookmarked

**Comment by lmorchard** [comment]
Looks like a literal `about:logins` URL is not feasible for web extensions per [bug 1322304](https://bugzilla.mozilla.org/show_bug.cgi?id=1322304).

There *is* [an omnibox keyword that can be set in manifest.json](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/omnibox). That lets us [hook into the URL bar to offer suggestions when the user types the keyword](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/omnibox). But, this isn't the same as a stable `about:logins` URL.

*Maybe* we could get a privileged API in Firefox for this? (i.e. registering an `about:*` page for Mozilla-signed extensions) But, [bug 1322304](https://bugzilla.mozilla.org/show_bug.cgi?id=1322304) makes me think that could controversial.

**Comment by sandysage** [comment]
Agreed. This is where we eventually want to go.

The path forward likely involves landing something in Firefox first and then this issue becomes more about how we point to it (override it?) to achieve the product acceptance.

**Comment by linuxwolf** [comment]
The current thinking is not that this webextension adds this URL directly, but rather the URL is established that this webextension then overrides (see #10).

However, the ultimate goal may still not be possible due to linking constraints on "about:" URLs.

**Comment by sandysage** [comment]
Waiting on support to land in Firefox.

**Comment by mnoorenberghe** [comment]
> * It isn't possible to take an about: URL to chrome/other browsers
> 
> * If a user has about:logins opened at startup, that won't load correctly, because webextensions don't start until after the browser has loaded all windows, so the about: page handler won't be registered in time
> 
> * about: pages have quirky constraints on security properties and communication with addon code, while built-in webextension pages make it really easy to communicate with the core addon code

All of the above are very true and make things much more complicated than they need to be to solve the original goal of being stable. Have we considered using a web origin like `https://passwords.firefox.com` as the user-facing URL that users would use to manage their logins from the extension? That would work in other browsers and also avoid the other issues outlined. If a user visits that site without the extension we would host copy to tell the user to install the extension/app (depending on OS). Thoughts?

**Comment by linuxwolf** [comment]
> All of the above are very true and make things much more complicated than they need to be to solve the original goal of being stable. Have we considered using a web origin like `https://passwords.firefox.com` as the user-facing URL that users would use to manage their logins from the extension? That would work in other browsers and also avoid the other issues outlined. If a user visits that site without the extension we would host copy to tell the user to install the extension/app (depending on OS). Thoughts?

That seems like a worthwhile approach.  There are a few ways we can try to accomplish this, though it seems to me the one with the least complications is via `webRequest` redirection.

**Comment by linuxwolf** [comment]
@mozilla-lockbox/product Note this issue is blocked on the following:
* using "about:logins" vs using a public URL
* the public URL to use

**Comment by sandysage** [comment]
Can we start with a web origin like https://passwords.firefox.com for the extension release? I'm expecting we'll want to introduce about:logins in Firefox but I don't _think_ these things are mutually exclusive. Am I introducing significant duplicate work to provide both this year?

I think the decision hinges on the preferred implementation approach for Firefox. 

cc @mnoorenberghe

**Comment by sandysage** [comment]
Given today's discussion, let's plan to consume about:logins. If/when we introduce Lockwise in other browsers we'll need to figure out what to do, but that is not the problem to solve right now.

I'm closing this issue as we'll not be addressing this in the extension.
