### ISSUE TITLE
Investigate building in m-c tree

### ISSUE THREAD

**Issue by 6a68** [mozilla-lockbox/lockbox-addon#144]
I expect we'll stick with exporting the built + source code into mozilla-central, like activity stream does, but we should briefly explore whether the copy of node in tree could be used to build the extension directly.

@dmose and/or @Standard8 are good contacts here.

**Comment by linuxwolf** [comment]
This work is being taken care of by front-end engineering; closing this issue.

**Comment by dmose** [comment]
@6a68 Activity-Stream is working on a plan to be increasingly m-c focussed over time.  This is not to say that we will necessarily let go of the github repo, though that's certainly possible.   The currently proposed success condition looks like this:

> All Activity Stream and related code is living and breathing as a first-class citizen in our Firefox Desktop monorepo (m-c), and is supported by the tooling that our release engineering and build teams maintain for that monorepo. The Github repo should not be required for any reason to make changes to Activity Stream/New Tab/CFR in Firefox.

Feel free to reach out to me if you'd like to chat more about this.
