### ISSUE TITLE
Review the test cases

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-addon#147]
Placeholder chore for the team to review:
https://docs.google.com/spreadsheets/d/1JdZxKx22KJOWoQB6jLBIqN_F3CGV1p-C5UdZ3Y51u44/edit#gid=0

**Comment by 6a68** [comment]
OK, I did a pretty thorough pass here. Happy to leave this open for others to review, but I'm good to close whenever.

**Comment by linuxwolf** [comment]
I think we're good to close.  It's quite thorough, and has already sussed out good things to fix.
