### ISSUE TITLE
"Duplicate Entry" error box stays visible

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-addon#150]
The "Duplicate Entry" error box does not dismiss when the user clicks cancel or otherwise moves away from editing.

## Steps to Reproduce

1. click "+" (add) or "Edit" (if an existing entry is selected)
2. enter "Website Address" and "Username" matching an existing entry
2. click "Create Entry" (or "Save")

   * Observe "Duplicate entries" error callout

3. cancel add

   1. click "Cancel"; then
   2. click "Dicard Changes"

4. attempt to add/edit another entry

**Expected:** no "duplicate error" callout
**Actual:** displays "duplicate error" callout

**Comment by 6a68** [comment]
Think I spotted the fix for this when working on #155: the `editor.error` state is set by ADD_ITEM_FAILED, but after completing the add/update, it isn't cleared, and there's no default state for the `error` property in the editor reducer.
