### ISSUE TITLE
The Lockbox extension doesn't have any specific icon in "about:addons" page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-lockbox/lockbox-addon#151]
[Affected Versions]:
- Lockbox 2.1.0-alpha
- Firefox 66.0.3 and up

[Affected Platforms]
- All Windows
- All Mac
- All Linux

[Perquisites]
- Have the latest Firefox 66.0.2 installed.
- Have a Firefox profile with the "xpinstall.signatures.dev-root" pref created and set to "true".
- Have the Lockbox 2.1.0 - alpha extension instaled.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to "about:addons" page and click the "Extension" section.
3. Observe the Lockbox extension.

[Expected results]:
- A specific icon is displayed for the extension.

[Actual results]:
- No icon is displayed.

[Notes]:
- Attached a screenshot with the issue:

![about addons](https://user-images.githubusercontent.com/19226534/56493383-96ba4400-64f7-11e9-8e26-9b17c170b738.png)

![locbox icon 2](https://user-images.githubusercontent.com/19226534/56493388-991c9e00-64f7-11e9-9f85-e41a57b1dd8c.png)

**Comment by linuxwolf** [comment]
As this identifies is part of the product brand identity, it should be the same Lockbox icon in use with the mobile apps

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue on the latest Lockwise 2.2.0-alpha version and the issue is no longer reproducible.
Tested on Windows 10 x64, Mac 10.14 and Ubuntu 18.04.
