### ISSUE TITLE
Copying password should update timeLastUsed

### ISSUE THREAD

**Issue by 6a68** [mozilla-lockbox/lockbox-addon#157]
When the password field is copied, I think we should increment the `timeLastUsed` field in the LoginManager, but it doesn't look like we currently do so. _(edit: not `timePasswordChanged`, `timeLastUsed`)_

Probably could update this in `background/message-ports.js`, in response to the "copied_field" message.

**Comment by linuxwolf** [comment]
The `timeLastUsed` should update, not the `timePasswordChanged`; the latter should only change if the user enters a new value when editing.

**Comment by 6a68** [comment]
Thanks, yeah, that was what I meant :-P
