### ISSUE TITLE
Derive entry titles from saved login URL

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-addon#16]
When viewing the entry list, I want to quickly scan the entry list by title (e.g., Facebook instead of https://www.facebook.com or even www.facebook.com), so I can quickly access my username and password for managing that record.

## Acceptance criteria

* Should be able to view the list of entries by the origin
* Default alphabetical ordering on the origin should make sense (eg facebook comes before twitter)
* Should not not include the protocol (http://, https://, www.)
* Should not see anything after the suffix (.com/{*})
* Should support future goals of editing the entry name

Requires #21

**Comment by 6a68** [comment]
> * Should support future goals of editing the entry name

I'm not sure we can make the entry name editable, if we're planning to stick with the existing nsILoginInfo/MetaData interfaces for storage (#21).

**Comment by linuxwolf** [comment]
> > * Should support future goals of editing the entry name
> 
> I'm not sure we can make the entry name editable, if we're planning to stick with the existing nsILoginInfo/MetaData interfaces for storage (#21).

Thats why it's a future goal (-:

**Comment by linuxwolf** [comment]
Consider placing this logic within the `browser.logins` API implementation, so we can utilize nsURL
