### ISSUE TITLE
"Saved Logins" window is wrongly opened instead of Lockwise page when the "View Saved Logins" option from context menu it's clicked on Firefox 66 release

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-lockbox/lockbox-addon#161]
[Affected Versions]:
- Lockbox 2.1.0-alpha
- Firefox 66.0.3

[Affected Platforms]
- All Windows
- All Mac
- All Linux

[Perquisites]
- Have the latest Firefox 66.0.3 installed.
- Have a Firefox profile with the "xpinstall.signatures.dev-root" pref created and set to "true".
- Have the Lockbox 2.1.0 - alpha extension instaled.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to a login page of a website.
3. Right click on the "Username" field.
4. Hover the "Fill login" option and click the "View Saved Logins" option.
5. Observe the behavior.

[Expected results]:
- The Lockwise page is correctly opened and all the saved logins are displayed.

[Actual results]:
- "Saved Logins" Firefox window is wrongly opened instead of Lockwise page.

[Regression]:
- Since the issue is not reproducible on latest Beta 67.0b12 build and latest Nightly 68.0a1 build, using mozregression tools I have managed to find a pushlog that include the changes that fixed the issues.
Here is the pushlog:
From the pushlog it seems that bug [**1529729** ](https://bugzilla.mozilla.org/show_bug.cgi?id=1529729)fixed this issue. Since the patch landed only on Firefox 67 and up, Firefox 66.0 release is still affected.

[Notes]:
- Attached a screen recording with the issue: 
![view saved logins](https://user-images.githubusercontent.com/19226534/56576158-4f53b680-65d0-11e9-96dc-7d5886ca7a58.gif)

**Comment by linuxwolf** [comment]
Product decision to increase minimum to 67.

Current minimum is implied to be 63, which was the bare minimum for WebExtension APIs we depended on.

**Comment by linuxwolf** [comment]
Connected to #168

**Comment by linuxwolf** [comment]
Closing now that the min version now 67+, where we can override the default.

* See #182 , #168

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue on the latest Lockwise 2.2.0-alpha version and the add-on is no longer compatible and cannot be installed on Firefox versions smaller than 67.
Tested on Windows 10 x64, Mac 10.14 and Ubuntu 18.04.
