### ISSUE TITLE
Logins created with "www" in the website address are not recognized if the website's url redirects without "www"

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-lockbox/lockbox-addon#162]
[Affected Versions]:
- Lockbox 2.1.0-alpha
- Firefox 66.0.3 and up

[Affected Platforms]
- All Windows
- All Mac
- All Linux

[Perquisites]
- Have the latest Firefox 66.0.3 installed.
- Have a Firefox profile with the "xpinstall.signatures.dev-root" pref created and set to "true".
- Have the Lockbox 2.1.0 - alpha extension instaled.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Create a new entry using the https://twitter.com/ website address.
3. Create a new entry using the https://www.twitter.com/ website address.
4. Launch any of the created entries.
5. Click the "Username" filed from the Twitter login page.
6. Observed the suggested logins.

[Expected results]:
- Both saved logins are displayed as a suggestion.

[Actual results]:
- The login created using the https://www.twitter.com/ website address is not displayed as a suggestion.

[Notes]:
- The hint for new entries wrongly implies that all domains must include "www", even if there are websites that redirect to a URL without "www".
- Attached a screen recording with the issue: 
![www domain](https://user-images.githubusercontent.com/19226534/56577538-e79f6a80-65d3-11e9-8014-7991c394635b.gif)

**Comment by linuxwolf** [comment]
As a starting point, the copy should probably change to remove mention of "www".

Anything further likely requires some work within the underlying autofill framework.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue on the latest Lockwise 2.2.0-alpha version and "www" is no longer required when creating a new login.
