### ISSUE TITLE
Clicking an entry from the doorhange does not launch it

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla-lockbox/lockbox-addon#164]
[Affected Versions]:
- Lockbox 2.1.0-alpha
- Firefox 66.0.3 and up

[Affected Platforms]
- All Windows
- All Linux
- All Mac

[Perquisites]
- The Lockbox 2.1.0-alpha add-on is installed.
- One or more entries were created.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Click the "Lockbox" toolbar button and click one of the entries from the doorhanger.
3. Observe the behavior.

[Expected results]:
- The website from the entry is launched and the doorhanger is closed.

[Actual results]:
- The entry's details are displayed and the website is not opened.

[Notes]:
- In the provided [mock-ups](https://mozilla.invisionapp.com/share/ENOL84959AK#/screens/338166656) (slides 33,39) the website is opened when clicking the doorhanger entry.
- Attached a screen recording of the issue:
![Lock_doorhanger_launch](https://user-images.githubusercontent.com/40393891/56579489-f2a8c980-65d8-11e9-9393-d51c680b7f10.gif)

**Comment by linuxwolf** [comment]
Filtering text needs to be updated to not say "select to launch".

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible using the lockwise-signed.xpi (2.2.0) add-on on Windows 10 x64, Arch Linux and Mac 10.14.4 using Firefox Beta 67.0b19.
