### ISSUE TITLE
The Lockbox tab icon is barely visible when the tab is not focused

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-lockbox/lockbox-addon#167]
[Notes]:
- If the Dark Theme is set, the Lockbox icon is not visible at all.

[Affected Versions]:
- Lockbox 2.1.0-alpha
- Firefox 66.0.3 and up

[Affected Platforms]
- All Windows
- All Mac
- All Linux

[Perquisites]
- Have the latest Firefox 66.0.3 installed.
- Have a Firefox profile with the "xpinstall.signatures.dev-root" pref created and set to "true".
- Have the Lockbox 2.1.0 - alpha extension instaled.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Click the "Lockbox" toolbar icon.
3. Click the "Open Lockbox" button from the displayed doorhanger.
4. Open a new tab.
5. Observe the Lockbox icon from the Lockbox tab.

[Expected results]:
- The icon is visible.

[Actual results]:
- The icon is barely visible.

[Additional Notes]:
- Attached a screenshot with the issue with default theme set:
![picturemessage_q1ilfse2 bas](https://user-images.githubusercontent.com/19226534/56587547-67383400-65ea-11e9-90c8-8daa993dbe02.png)

- Attached a screenshot with the issue with dark theme:
![picturemessage_0utollig 2sn](https://user-images.githubusercontent.com/19226534/56587561-6bfce800-65ea-11e9-927a-782522ad9ac2.png)

**Comment by linuxwolf** [comment]
Switch to using the Lockbox app icon instead of the doorhanger icon

**Comment by 6a68** [comment]
It looks like native icon color switching via context-fill is not available to webextensions in the tab icon. There is basic support for dark/light mode switching for toolbar icons, but not for tab icons, see https://bugzilla.mozilla.org/show_bug.cgi?id=1377302 (and the constellation of related bugs).

I'm guessing we will be changing the app icon as part of the rebranding effort; throwing this back on the pile for now.

**Comment by linuxwolf** [comment]
> I'm guessing we will be changing the app icon as part of the rebranding effort; throwing this back on the pile for now.

My thinking is taking care of this now, while seemingly duplicative, would make rebranding easier (search for _X_ and replace with _Y_).

**Comment by 6a68** [comment]
:+1:

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue on the latest Lockwise 2.2.0-alpha version and the issue is no longer reproducible. Tested on Windows 7 x64, Mac 10.14 and Arch Linux 4.12 with default, dark and light themes.
