### ISSUE TITLE
The "breach notification" functionality is mentioned in Lockbox onboarding page even if it's not yet implemented

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-lockbox/lockbox-addon#174]
[Affected Versions]:
- Lockbox 2.1.0-alpha
- Firefox 67 and up

[Affected Platforms]
- All Windows
- All Mac
- All Linux

[Perquisites]
- Have the latest Firefox 67 version installed.
- Have the Lockbox 2.1.0 - alpha extension installed.
- Have no saved logins.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Click on the Lockbox tollbar button.
3. Click the "Open Lockbox" button from the displayed doorhanger.
4. Observe the Lockbox onboarding page.

[Expected results]:
- The page is correctly displayed.

[Actual results]:
- "Get notified when new breaches occur" section is displayed, even if the notification is not yet implemented.

[Notes]:
- Attached a screenshot with the issue:
![homepage](https://user-images.githubusercontent.com/19226534/56645680-cf3c5800-6686-11e9-8b1c-8ed1083911ec.png)

**Comment by linuxwolf** [comment]
There are no plans to support breach notifications with the first release, so I think the section needs to go.

@changecourse do you have a preference on how to handle this? (ordered by eng difficulty)
* Simply remove the section, and leave the "gap"
* Change layout to a single column 
* Reflow bottom-left section ("Quick acces to your logins") to span both columns

**Comment by changecourse** [comment]
> Simply remove the section, and leave the "gap"

Works for me.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue on the latest Lockwise 2.2.0-alpha version and the issue is no longer reproducible. The "Get notified when new breaches occur" section is no displayed.
