### ISSUE TITLE
Error Handling: "missing password" on add/edit save

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-addon#18]
The password cannot be empty.

## Visual Design
**InVision**
https://mozilla.invisionapp.com/share/ENOL84959AK#/339614518_Logins_-_New_Entry_-_Error_-_Password_-Light-

**Zeplin**
https://zpl.io/Vkweq3L

**Comment by nickbrandt** [comment]
@sandysage is the open question just regarding the user choosing to Edit this entry, and then not being able to save it without a password? I think this is still fine to require the user to enter a password (or cancel out if they choose), as the entry won't be valuable without a password attached anyways.

**Comment by sandysage** [comment]
For context, I deleted the open question.
