### ISSUE TITLE
Fluent files have errors

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-addon#193]
The existing fluent files have the following errors:

* `list-count occurs 2 times`
* ` filtered-banner occurs 2 times`

**Comment by linuxwolf** [comment]
@Pike what's the best way for us to lint/anyalyze our fluent files?

**Comment by Pike** [comment]
Hi Matthew, I uploaded my `l10n.toml` file in PR #194, which allows you to run the same checks I run locally.
