### ISSUE TITLE
"Reveal Password" functionality

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-addon#20]
When I want to access an account on a different device, or copy/paste doesn’t work for me, I want to see the password so I can manually enter it to get into my account.

## Acceptance criteria

* Should be able to view password from detail view

## Visual Design

**InVision**

**Zeplin**
Password Hidden (default): https://zpl.io/boK9ggk
Password Shown: https://zpl.io/bzARAzX
Password - Long (read version): https://zpl.io/aMKJOzK
Password - Long (edit mode): https://zpl.io/adrvOB7 (field would be scrollable)

**Comment by 6a68** [comment]
Do we want to reveal details in the doorhanger as well as the mgmt UI?

**Comment by linuxwolf** [comment]
Both Zeplin links are failing with a "Screen not available anymore" dialog.

**Comment by nickbrandt** [comment]
@linuxwolf sorry about that, should be good now
