### ISSUE TITLE
Implement Sync WebExtension API (Browser.sync API)

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-addon#23]
A Sync API to function post Firefox 64 for the Lockbox add-on to access state information related to Firefox Sync.

## Requirements

* Determine if browser-wide sync is available (i.e., signed in to FxA)
* Determine if syncing of <type> is enabled (i.e., relevant pref is `true`).
* Provide sync profile information (i.e., FxA profile), if available
* Notification when profile information/state changes (in-browser changes)

## Risks

* security concerns
  * Privileged addons + “sync” permission for profile information (contains PII)
  * Sync state (inactive / disabled / enabled) privileged?
* implementation concerns
  * at least some portions of this are already defined in [`chrome.identity`](https://developer.chrome.com/extensions/identity); marked as "unsupported" within Firefox as of 65

**Comment by 6a68** [comment]
We can do this as an embedded API experiment right away, separately from the question of getting approval to land in Firefox. Should unblock the sync-related UI issues/design work (#38)

**Comment by Riajyuu** [comment]
just a question here:
what would you like to do with https://bugzilla.mozilla.org/show_bug.cgi?id=1316442
