### ISSUE TITLE
Integration test startup errors

### ISSUE THREAD

**Issue by 6a68** [mozilla-lockbox/lockbox-addon#27]
When running the integration tests locally, I'm getting failures with this error:

`JavascriptError: Error: resource://gre/modules/Services.jsm - Couldn't find target object for import.`

Looks like the driver setup is tripping on [this spot](https://searchfox.org/mozilla-central/source/js/xpconnect/loader/mozJSComponentLoader.cpp#1004) in the script loader. Maybe there's some flag we need to set for it to allow the test to load the script.

Related to #22.

**Comment by linuxwolf** [comment]
Hrm, that is interesting, and not my experience (macos 10.14 + Firefox nightly) nor Travis-CI's (ubuntu + Firefox unsigned release).  Can you provide some platform info (OS and Firefox version/channel)?

**Comment by 6a68** [comment]
Yeah, I'm on mac 10.13.6 and latest nightly.

After poking around a bit, I tried changing the `ChromeUtils` incantation slightly, and now the tests run and pass. I'll push up a PR to see if there are any differences that you or CI notice

**Comment by linuxwolf** [comment]
fixed in PR #28
