### ISSUE TITLE
Add telemetry events for relevant actions in the extension

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-addon#29]
As the product owner, I want to know how users engage with the app to help inform decisions for future effort, while making sure users have control over whether or not their usage data is submitted.

## Acceptance criteria

* All events should send Telemetry event data defined by the Mozilla product, data science, and legal teams
* The user should be able to disable usage data collection (Telemetry) via a setting

**Comment by sandysage** [comment]
I think this probably starts as modifying [the existing metrics.md](https://github.com/mozilla-lockbox/lockbox-addon/blob/master/docs/metrics.md).

**Comment by 6a68** [comment]
Implementation will be straightforward: the telemetry API exposes everything we need. Most of the work in this bug will be the legal & data reviews.

**Comment by 6a68** [comment]
> Most of the work in this bug will be the legal & data reviews.

🤣
