### ISSUE TITLE
Error handling: Web Address must contain "https://" or "http://" 

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-addon#30]
The Web Address must contain a scheme (e.g., "https://") and a host (domain + port), and must not include a path.

If the URI is not well-formed, an error is displayed suggesting the user include "https://".

If the URI is well-formed but includes a path, the path can be stripped.

## Implementation Details

* Start using web URL class for validation.
* Extra testing to be sure URL class is sufficient.

## Visual Design
**InVision**
Helper: https://mozilla.invisionapp.com/share/ENOL84959AK#/339614514_Logins_-_New_Entry_-_Address_Focused_-Light-
Error: https://mozilla.invisionapp.com/share/ENOL84959AK#/339614519_Logins_-_New_Entry_-_Error_-_Address_-Light-

**Zeplin**
Helper: https://zpl.io/andLDWA
Error: https://zpl.io/aNKzXWk

**Comment by linuxwolf** [comment]
We should only add "https://" if we're massaging data.  If we're informing the user of an error they need to correct, then we can indicate either, preferring "https://".

**Comment by sandysage** [comment]
Convert to URI to strop off the end. Deliver error message if http:/ or https:/ is missing
