### ISSUE TITLE
View Details of an Entry

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-addon#33]
When I select an entry -- in either the management interface or the doorhanger -- I want to see its details and understand what actions I can take.

## Acceptance Criteria
* _to be defined_

## Visual Design
**InVision**
Full View: https://mozilla.invisionapp.com/share/ENOL84959AK#/338158445_Logins_-_Home_-Light-
Full View - Long passwords: https://mozilla.invisionapp.com/share/ENOL84959AK#/340867861_Logins_-_Entry_Detail_-_Long_Password_-Light-
Doorhanger: https://mozilla.invisionapp.com/share/ENOL84959AK#/338166659_Doorhanger_-_Entry_Detail_-Light-

**Zeplin**
Full View: https://zpl.io/boK9ggk
Full View - Long passwords: https://zpl.io/aMKJOzK
Doorhanger: https://zpl.io/2pnBL78

**Comment by meandavejustice** [comment]
@devinreams Do we have the url for the `Learn More` link to download the mobile app yet?

**Comment by meandavejustice** [comment]
Just noticed the edit button in the icon of the doorhanger, we won't be able to add that(functionally) until #13 is fixed i believe(not sure how else we would link to an edit entry)

Seems out of scope for this issue. Filed #86

**Comment by devinreams** [comment]
>@devinreams Do we have the url for the `Learn More` link to download the mobile app yet?

I think we'd be safe to put in https://lockbox.firefox.com/ right now and can revisit if we have a more specific location we'd drive users to.

Happy to defer to @sandysage or the team if there was another one already in mind that I missed...
