### ISSUE TITLE
Search entries in both management interface and doorhanger

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-addon#36]
When I have several Lockbox entries and I need to access an online account, I need to be able to quickly find an entry by website address, entry name, or username. Both in the doorhanger and the management interface.

## Acceptance criteria
* [x] Should filter results based on characters entered in the search field
* [x] Should display matching results by: title, URL, username
* [ ] Should provide additional information to the user if no matching entries are found

## Visual Design

**Full View**
Default (focused): https://zpl.io/boK9ggk
Searching: https://zpl.io/bldPRR5
Not Focused: https://zpl.io/am94zze
No Matching Results*: https://zpl.io/bzAOPkE

**Doorhanger**
Default(focused): https://zpl.io/2EPeOpy
Searching: https://zpl.io/25G8Jln
Not Focused: https://zpl.io/VQK46qW
No Matching Results*: https://zpl.io/agP3rj9

*Link for no matching results directs here: https://lockbox.firefox.com/faq.html#how-do-i-get-my-saved-logins-into-firefox-lockbox

**Comment by 6a68** [comment]
The search features seem to be in the addon already. Closing.

**Comment by nickbrandt** [comment]
@6a68 although the functionality of this is already built, there have been some changes in the styling since this was completed for the extension. In addition, there are changes in copy/styling for the No Results when searching. Should I create those as new issues, or would you rather we re-open this issue and adjust it to reflect the work that needs done?

**Comment by linuxwolf** [comment]
Just about all of search is shared components, so re-opening this issue is best.

**Comment by linuxwolf** [comment]
Most of the requirements were implemented as part of earlier issues/PR, leaving only the "No Matching Entries" details to be done.
