### ISSUE TITLE
Display FxA profile (Management UI)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-addon#37]
Child of #38

As a user, I want to know that I am signed in with Firefox Account (FxA).

### Acceptance Criteria
* Should keep the "Logins" tab, but not display the "Monitor" tab for now
* Should render FxA information if we have it, otherwise we need to show a 'guest' state if you're not signed in (need follow up stories for how we promote people to sign in)

### Engineering Notes

* This issue includes updating/modifying the "header" to match the current tabs-like visuals.
* The avatar image does **NOT** include the circle border (URL links to a "square" avatar)
* The `avatarURL` property is always set (using the default if the user has not uploaded one)
* Use `displayName` if set, otherwise `email`

### Visual Design
**Zeplin**
https://zpl.io/boK9ggk (current, may change depending on experiment)

**Comment by 6a68** [comment]
I asked around for details on the profile avatar discussion, and was directed to the #fxa-sync-ux Slack channel. Might be worth idling in there to keep tabs on their progress

**Comment by linuxwolf** [comment]
There is an effort to define some experimental APIs that would cover this.
