### ISSUE TITLE
EPIC: Promote turning on Sync (signing up for FxA)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-addon#38]
When using the Lockbox extension, I want to know how to set it up so that I can easily access on mobile.

## Acceptance criteria
* Should include a call to action to sign up for FxA if not already (can we detect #23)
* Should include a call to action to turn on Sync for logins if not already (can we detect #23)
- [x] #61 
- [x] #72 
- [x] #14 
- [x] #37
- [x] #79
- [x] #92
- [x] #97

## Visual Design
**InVision**
User Menu (not signed in)
https://mozilla.invisionapp.com/share/ENOL84959AK#/339623981_Logins_-_Home_-_Menu_-_Not_Signed_In_-Light-

Connect Device Modal - Needs to sign in
https://mozilla.invisionapp.com/share/ENOL84959AK#/342439032_Logins_-_Connect_Device_-_Not_Signed_In_-Light-

Connect Device Modal - Needs to check "logins" in sync pref
https://mozilla.invisionapp.com/share/ENOL84959AK#/342439031_Logins_-_Connect_Device_-_Logins_Not_Checked_-Light-

Connect Device Modal - Steps complete (transitions to instruction screen)
https://mozilla.invisionapp.com/share/ENOL84959AK#/343764712_Logins_-_Connect_Device_-_Steps_Complete_-Light-

Connect Device Modal - Instructions (what a user would see if they were already signed in and selected "Connect a Device" from the user menu)
https://mozilla.invisionapp.com/share/ENOL84959AK#/343764713_Logins_-_Connect_Device_-_Instructions_-Light-

**Zeplin**
User Menu (not signed in): https://zpl.io/a8pvROX
Connect Device Modal - Needs to sign in: https://zpl.io/aByAXxp
Connect Device Modal - Needs to check "logins" in sync pref: https://zpl.io/a8pqXgw
Connect Device Modal - Steps complete (transitions to instruction screen): https://zpl.io/boKE38E
Connect Device Modal - Instructions: https://zpl.io/VqK43Ym

* depends on #23

**Comment by nickbrandt** [comment]
@linuxwolf @6a68 I'ved added some designs to this issue around how we would like to handle promoting sync and connecting additional designs. Would like to get your thoughts on these, whether that be async or a quick vidyo chat.

**Comment by linuxwolf** [comment]
@nickbrandt let's try async.

Assuming the Invision/Zeplin links above are correct, my comments/questions right now are:

* We have detection, so I don't think we have to worry about option #1 anymore
* Is the modal triggered from the "Learn More" promotional?
* How much state checking is expected here? For example, should "1" change to "✓" as soon as sign in is detected?
* Does this modal close only when the user clicks "Done", or does it happen automatically if we detect sync is now enabled?
* Related; does "2" change to "✓" as soon as we detect it's enabled?

Note, our current Sync state implementation does not have an event listener, so we'll need to poll for it or see about adding a event listener.

**Comment by nickbrandt** [comment]
@linuxwolf thanks for your feedback. I've included some additional context below, as well as added a screen

> We have detection, so I don't think we have to worry about option #1 anymore
Good to know, thanks 👍 

> Is the modal triggered from the "Learn More" promotional?
No, the plan for that promo is to actually link to the Lockbox website where we will have information about the mobile apps (as well as sync requirements)

The modal in these designs would be initiated by selecting the "Connect a Device" option from the user menu. If the user is already signed in to sync (and has logins checked in sync prefs), they would see the [Instructions screen](https://zpl.io/VqK43Ym). If they are not signed in, or do not have logins checked in sync prefs, they would see [this modal](https://zpl.io/aByAXxp) at whichever step they are at.

> How much state checking is expected here? For example, should "1" change to "✓" as soon as sign in is detected?
The hope would be yes, that after signing in, that screen would update to reflect the state they are in (either both steps complete or still needing to check logins). After both of those tasks are complete, the content in this modal would transition to the [Instructions screen](https://zpl.io/VqK43Ym), to inform the user how to connect a device now that they are signed in.

> Does this modal close only when the user clicks "Done", or does it happen automatically if we detect sync is now enabled?
Yes (this has been updated to "Close"), the user can close the modal by either clicking outside of it, clicking the "x", or selecting "Close". Similarly, once they are on the instructions screen, they would use the same options to close the modal (button says "All Set" here).

> Related; does "2" change to "✓" as soon as we detect it's enabled?
As stated above, the hope would be yes. Upon finishing the second step (or both steps completing at once), show both items as being complete and then transitioning to the Instructions screen.

I know this is a lot to digest here, so let me know if you'd like to discuss to understand this any better!

**Comment by linuxwolf** [comment]
@nickbrandt this helps tremendously, thank you!

I completely missed the user menu, and this makes sense to me for someone not signed in.  I think we'll need to explore this menu further as it could be a path to account for the edge cases in #61.

I think we can begin to break this down into smaller tasks now, though.

**Comment by sandysage** [comment]
A little house cleaning, we're now tracking the user menu in #72

**Comment by sandysage** [comment]
Closing this epic as complete as all the stories associated with this issue are done
