### ISSUE TITLE
Toolbar icon

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-addon#39]
When I want to access my passwords, I need a quick way from anywhere I am to get to that interface.

## Acceptance criteria
* Should have an icon that persists in the toolbar so I can always access my saved logins
* Should not have a locked/unlocked state (previous extension) and the icon needs to be persistent no matter if the user is signed in or not
   * this might be introduced again at a later time, but we're intentionally removing for now

## Visual Design
**InVision**
https://mozilla.invisionapp.com/share/ENOL84959AK#/331897167_Lockbox_-_Doorhanger_-_New_Tab

**Zeplin**
https://zpl.io/boK9ggk

[Lockbox.svg.zip](https://github.com/mozilla-lockbox/lockbox-addon/files/2700563/Lockbox.svg.zip)

**Comment by linuxwolf** [comment]
Requirements here already addressed during port from original `lockbox-extension` codebase.
