### ISSUE TITLE
Implement Logins WebExtension API (Browser.logins API)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-addon#4]
A Logins API is necessary to function post Firefox 64 for the Lockbox add-on to access browser saved logins.

## Requirements
* Retrieve all login items
* Retrieve a specific item by ID
* Create a new login item
* Update an existing login item (by ID)
* Delete an existing login item by ID
* Notification when a login is changed (added, updated, removed)

## Risks
* Usability concerns
   * Prevent the extension’s web content (e.g., “management UX”) from triggering “save this login?” prompts (i.e., URL from Add extension’s URL to the list of disallowed hosts (for prompting to save logins)
* Security concerns
   * No permission needed to store extension’s “own” logins (by extension ID?)
   * Privileged addons + “logins”  permissions for access to all logins (PII and highly sensitive data!)
   * Including Favicons might be a privacy leak or concern?

**Comment by 6a68** [comment]
Useful test code: https://github.com/web-ext-experiments/logins/blob/master/test/test_ext_logins.js
