### ISSUE TITLE
Investigate CI pipeline integrations with autograph service

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-addon#44]
Determine what it would take to pass through the autograph service and integrate with our build process.

Potentially involves switching from TravisCI to CircleCI.

## Acceptance Criteria
* Approach for automatically publishing a Mozilla-signed addon is documented
* Follow-up issues to track making the necessary changes are created

**Comment by devinreams** [comment]
Bug to request/discuss autograph signing keys opened here: https://bugzilla.mozilla.org/show_bug.cgi?id=1530398

**Comment by meandavejustice** [comment]
Where do we want to upload the addon once it is signed? a gh release maybe for the time being?

**Comment by linuxwolf** [comment]
> Where do we want to upload the addon once it is signed? a gh release maybe for the time being?

For non-production (`master`) builds, can we leave them on CircleCI?  As a starting point, I think it's acceptable if only members of `mozilla-lockbox` can get to those artifacts.

For `production` builds it makes sense to use GH releases, as a starting point.

[ note to self + @devinreams -- setup a `production` branch ]

**Comment by devinreams** [comment]
>For production builds it makes sense to use GH releases, as a starting point.
>[ note to self + @devinreams -- setup a production branch ]

Added production branch (off master) and set as a "protected" branch (no force pushes, can't delete).

**Comment by meandavejustice** [comment]
fixed in #98
