### ISSUE TITLE
Implement auto-update support

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-addon#45]
## To do

* [ ] Create and deploy initial [update manifest](https://developer.mozilla.org/en-US/Add-ons/Updates) file
* [ ] Add update hook in [extension manifest](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings#Firefox_(Gecko)_properties)

**Comment by linuxwolf** [comment]
closing in favor of #141
