### ISSUE TITLE
Create a New Entry in management area

### ISSUE THREAD

**Issue by nickbrandt** [mozilla-lockbox/lockbox-addon#48]
This is just a placeholder, as @linuxwolf mentioned this functionality would also be included, as we already have create support in the code base.

**Comment by nickbrandt** [comment]
@linuxwolf will Entry Name be a field when creating a new entry? Or will that be down the line, as we currently don't sync the Entry Name field

**Comment by linuxwolf** [comment]
@nickbrandt Entry Name cannot be an editable field yet.  I don't think it is worth adding fields until we can be sure they sync.

**Comment by linuxwolf** [comment]
implemented as part of #34
