### ISSUE TITLE
Use Telemetry WebExtension API (privileged)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-addon#5]
As the product owner, I want to know how users engage with the extension to help inform decisions for future effort, while making sure users have control over whether or not their usage data is submitted.

## Acceptance criteria
* All events should send Telemetry event data defined by the Mozilla product, data science, and legal teams
* The user should be able to disable usage data collection (Telemetry) via a setting
* Should use the new Telemetry API as it's necessary to function post Firefox 64

**Comment by linuxwolf** [comment]
This _should_ be done as part of migrating to this repo, but need to confirm.

**Comment by 6a68** [comment]
This was done as part of #29
