### ISSUE TITLE
Reveal password icon is misaligned

### ISSUE THREAD

**Issue by meandavejustice** [mozilla-lockbox/lockbox-addon#52]
refs #20 

![reveal](https://user-images.githubusercontent.com/1844554/50840890-8065ef00-1331-11e9-901c-e91c98b520d8.png)

**Comment by linuxwolf** [comment]
Appears to be fixed via #84 

![image](https://user-images.githubusercontent.com/757401/56613873-d145de80-65d4-11e9-8109-d072b1f12a2d.png)
