### ISSUE TITLE
Inform user of Sync/FxA errors

### ISSUE THREAD

**Issue by 6a68** [mozilla-lockbox/lockbox-addon#61]
Child of #38 

If the user is logged in to Sync, there are two edge cases we might bump into:

1) their email is unverified
2) their password was changed on another device, so the locally-cached password is stale, and they need to sign in again to sync

In both cases, the existing desktop code redirects the user to the sync preferences page (about:preferences#sync) to fix their situation.

## Acceptance criteria
* Should redirect to the same endpoint
* Should alert the user when the email is unverified
* Should alert the user when the Account password changed
* Should define own entrypoint in telemetry

Open questions:
- Product: Do we want to just redirect to that same endpoint? Assuming yes, more questions:
- Eng: We should be able to open the correct link via either `gSync.openPrefs` or `gSync.openSignInAgainPage()` ([usage example](https://searchfox.org/mozilla-central/rev/c21d6620d384dfb13ede6054015da05a6353b899/browser/base/content/browser-sync.js#279-283)) from an embedded API experiment. Need to make sure `gSync` is available in an API experiment js file (it should be).
- UX: What kind of UX do we want to offer in Lockbox for those cases? Some kind of info screen and a button to redirect to the preferences page? Show an alert badge over the icon?
- Telemetry question: The existing desktop hamburger menu item appends a query string when sending users to the sync preferences page: "about:preferences?entrypoint=menupanel#sync". Do we need to register a new entrypoint? (markh's thinking was that this query string is part of fxa server telemetry, ingested via amplitude, so, maybe it's dynamic and "entrypoint=lockbox" doesn't need to be explicitly registered anywhere)

### Visual Design

**InVision**
Full View: https://mozilla.invisionapp.com/share/ENOL84959AK#/343774936_Logins_-_Sync_Issue_-Light-
Full View - User Menu: https://mozilla.invisionapp.com/share/ENOL84959AK#/343989952_Logins_-_Sync_Issue_-_Menu_-Light-
Doorhanger: https://mozilla.invisionapp.com/share/ENOL84959AK#/343777425_Doorhanger_-_Sync_Issue_-Light-

**Zeplin**
Full View: https://zpl.io/2ZjOwLJ
Full View - User Menu: https://zpl.io/adrod9e
Doorhanger: https://zpl.io/VOKELQl

*Link would direct to sync preferences

Requires #92

**Comment by linuxwolf** [comment]
From an IRL discussion between @6a68 and I:

* The distinction between "email is unverified" and "password was changed/invalidated" is likely irrelevant to Lockbox; the user action ("Go to Sync preferences and follow the directions") is the same.
* The moment-in-time account status (none/active/failed) is readily obtainable (technical details ensue):
  - `none` is _currently_ in the API proposal as returning no profile
  - `active` is in the API proposal as returning a profile
  - `failed` is not yet in the API proposal

**Comment by 6a68** [comment]
Nick was asking for some UX details on Slack, and it occurs to me that it would be good info to include here:

-----

When your password becomes stale, if the hamburger menu is closed, it gets a little caution icon badge:

<img width="130" alt="screen shot 2019-01-29 at 1 20 48 pm" src="https://user-images.githubusercontent.com/96396/51942942-1d65f600-23cd-11e9-87ef-3c353023c027.png">

When you open the hamburger menu, the Sync menu item is highlighted yellow, and a warning message is shown:

<img width="250" alt="screen shot" src="https://user-images.githubusercontent.com/96396/51943203-c14fa180-23cd-11e9-9a95-1accbddb246d.png">


Clicking on the sync menu item goes to the usual `about:preferences#sync` page, which shows some explanatory messaging, along with buttons to sign in or disconnect sync:

<img width="811" alt="screen shot 2019-01-29 at 1 20 59 pm" src="https://user-images.githubusercontent.com/96396/51943037-5d2cdd80-23cd-11e9-9a27-bf7ddcbbd4da.png">

Note that we can use special built-in Firefox code to take users from the Lockbox management UI directly to the Sync page shown above.

**Comment by irrationalagent** [comment]
@6a68 I think we should definitely define our own entrypoint, my suggestion would be `lockbox-extension` or similar, not just `lockbox` because that may show up in the fxa telemetry elsewhere e.g. in the mobile apps. 

the parameter value has to pass the regex documented [here](https://mozilla.github.io/application-services/docs/accounts/metrics.html)
