### ISSUE TITLE
Clear clipboard after `copy`

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-addon#7]
## Acceptance criteria
* similar to mobile apps, should clear the clipboard 1 minute after a username and/or password is copied into it

## References
* [Clipboard API (MDN)](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API)

**Comment by linuxwolf** [comment]
Good news -- the current codebase does clear the clipboard after copy.
Bad news -- it clears after 2 seconds, and only if the page that executed the copy is still active.

The "best fit" solution is to migrate to the [async Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard).

**Comment by linuxwolf** [comment]
That is a problem I can fix ... standby (-:
