### ISSUE TITLE
Implement Sync/Profile user menu

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-addon#72]
Child of #38

## Acceptance criteria

* Clicking on display name/email or avatar should open menu
* Clicking outside of menu should dismiss it
* ESC key should dismiss it

## Visual Design
**InVision**
Signed In: https://mozilla.invisionapp.com/share/ENOL84959AK#/338158451_Logins_-_Home_-_Menu_-Light-
Not Signed In: https://mozilla.invisionapp.com/share/ENOL84959AK#/339623981_Logins_-_Home_-_Menu_-_Not_Signed_In_-Light-
Hover: https://mozilla.invisionapp.com/share/ENOL84959AK#/344286028_Logins_-_Home_-_Menu_-_Hover_-Light-

**Zeplin**
Signed In: https://zpl.io/aRWJ48g
Not Signed In: https://zpl.io/a8pvROX
Hover: https://zpl.io/VQKLLYA

## Implementation Notes
* **FAQ Link:** https://lockbox.firefox.com/faq.html
* **Feedback form:** _TBD_

**Comment by linuxwolf** [comment]
@ssage @nickbrandt @changecourse need links for the following website assets:
* FAQ (desktop)
* Provide Feedback (desktop)

**Comment by linuxwolf** [comment]
From planning, create a separate issue to address accessibility questions/concerns.
