### ISSUE TITLE
Promote FxA/Sync sign in when user is not logged in

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-addon#79]
When I'm not signed in with a FxA to Sync (specifically Sync for logins), I need to first know how to do that.

## Acceptance criteria
* Sign in to FxA and Sync should be the primary call to action if someone is not already
* Should promote the sign in from the top navigation

To consider: do we want to change the promotion at the bottom of the screen when not signed in?

## Visuals
![Logins - Home, unauthenticated (Light)](https://user-images.githubusercontent.com/6164801/54559398-96250f80-4985-11e9-82dc-a12d170e8696.png)

related #78
child of #38

**Comment by jawz101** [comment]
Why would FxA/Sync for the browser continue to sync passwords amongst devices?  That is, why couldn't Firefox have its local pw manager but then direct to lockbox at the point you want to sync pw's?  I'd argue it should be the way to sync both pw's and bookmarks ... or that's the direction I'd think would be neat.

**Comment by sandysage** [comment]
IRL discussion with Ryan, we do need to do a specific 'promotion' for signing into FxA/Sync. Leaving the flow as an open question (where we display the promo and how).

@changecourse is aware of this open request. It's my understanding he will not have an opportunity to provide designs here until the end of March given other commitments on Monitor.

**Comment by sandysage** [comment]
I propose we move forward  with changing the promotion at the bottom of the screen to promote "sign in to get access across devices" when not signed in.

@changecourse can you provide assets for that promotion?

**Comment by changecourse** [comment]
@sandysage do we need more than just a copy change for header/subheader and CTA for the unauthenticated state? See attached mock-up. (we may need some copy love before finalizing)

![Logins - Home, unauthenticated (Light)](https://user-images.githubusercontent.com/6164801/54559398-96250f80-4985-11e9-82dc-a12d170e8696.png)
