### ISSUE TITLE
Open FxA/Sync Account Details

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-addon#92]
As a user, I want to be taken to where I can manage my account and sync information.

### Acceptance Criteria
* Should be able to navigate to Account details from the drop down menu as created in #72 - to either sign in if not already or to manage my existing signed in state - about:preferences#sync

### Implementation Details
* Add a "service" parameter for telemetry noting Lockbox is the source

### Visual Design
* https://mozilla.invisionapp.com/share/ENOL84959AK#/screens/338158451

child of #38

**Comment by linuxwolf** [comment]
As a user, I want to be taken to where I can manage my account and sync information.

## Acceptance Criteria

## Visual Design

* https://mozilla.invisionapp.com/share/ENOL84959AK#/screens/338158451

**Comment by meandavejustice** [comment]
more info in #61
