### ISSUE TITLE
Connect another device

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-addon#97]
When I'm engaging the Lockbox interface, I want to know how to connect another device - get my logins in all the places I need to get into my accounts.

## Acceptance criteria
* Should support a Lockbox user to connect another device
* Should demonstrate the value of an Account (why you need to register or sign in) to connect another device
* Should align to the FxA flows for "connect another device"

**Comment by 6a68** [comment]
@ssage Is this the UX for this bug? https://app.zeplin.io/project/5c1829b8fde4d550a26b270f/screen/5c61fcc82e306c9a398f7ca0

**Comment by sandysage** [comment]
@6a68 Yes. That is the UX for this issue. Let me know if we need to split this out to better encompass the work.

**Comment by sandysage** [comment]
changing the "close" button to read "next" and the flow is progressive. no timer needed

**Comment by 6a68** [comment]
Discussion from planning: might not need to put the logins sync state in the redux store. Just call `browser.experiments.sync.getUserProfileInfo` to decide whether to check the first box, and `browser.experiments.sync.getCurrentState("passwords")` to decide whether to check the second box. If both boxes are checked, flip directly to the second view.
